### PR TITLE
Use `assign` instead of deprecated `merge`

### PR DESCRIPTION
**Pull request by wagenet**

### CODE REVIEW

**Comment by wagenet** [comment]
@cibernox doesn't look like the failing test is my fault, but can you verify?

**Comment by rwjblue** [comment]
No, we need to remove `^` from ember-try in package.json

**Comment by wagenet** [comment]
So is this good to merge?

**Comment by rwjblue** [comment]
Rebased and updated to add ember-assign-polyfill as a dependency.

**Pull request merged**
