### PR TITLE
Replace hard-coded guides link with /current

### PR DESCRIPTION
**Pull request by acorncom**
This type of link works fine for guides at this point.  We might also want to use the Ember version of the app in question, thoughts?

### CODE REVIEW

**Comment by Turbo87** [comment]
@acorncom what happens if the guides are restructured at some point and the link no longer points to anything useful?

**Comment by rwjblue** [comment]
@acorncom - Is this still the best path forward?

**Comment by acorncom** [comment]
@rwjblue yes, that URL should be fine. Are you referring to the current vs latest discussion we had a few months ago?

**Comment by rwjblue** [comment]
Ya, but I mostly just want to see if this is the right path forward, rebase, and merge if it is...

**Comment by rwjblue** [comment]
Needs a rebase 😭

**Comment by acorncom** [comment]
@rwjblue / @Turbo87 at long last, the PR rebase as requested. Sorry it's taken so long ...

**Comment by rwjblue** [comment]
No worries!

**Pull request merged**
