### PR TITLE
Upgrade @ember/test-waiters to 3.0.0

### PR DESCRIPTION
**Pull request by stefanpenner**
- `@emberjs/test-waiters`
- add ember-source 3.24 to ember-try

### CODE REVIEW

**Review by scalvert — APPROVED** [review]

**Review by scalvert — APPROVED** [review]
Thanks for adding the 3.24 scenario!

**Comment by Turbo87** [comment]
@stefanpenner this appears to be a breaking change (see https://github.com/rust-lang/crates.io/pull/3840). we are using ember-cli-dependency-lint to avoid having multiple versions of the same addon in the app, and now we have two different major versions of `@ember/test-waiters` that can't be deduplicated.

**Comment by scalvert** [comment]
Hey @Turbo87, `@ember/test-waiters` has a mechanism that [dedupes that dependency at build time](https://github.com/emberjs/ember-test-waiters/blob/master/force-highlander-addon.js), which helps ensure you only have one version at any time in your project. Is this manifesting as an actual issue, or are you just anticipating this based on how current ember-cli build dedupes work?

**Comment by stefanpenner** [comment]
@Turbo87 yes, it is a major version...

**Comment by scalvert** [comment]
I think you can accommodate this dependency using:

```json
// config/dependency-lint.js
module.exports = {
  allowedVersions: {
    '@ember/test-waiters': '*'
  }
};
```

**Comment by Turbo87** [comment]
@scalvert TIL, thank you. I've opened https://github.com/salsify/ember-cli-dependency-lint/pull/22 to adjust the default list of `allowedVersions` in that linter.

**Pull request merged**
