### PR TITLE
Update API.md

### LINKED ISSUE #542: Documentation Issues
- [x] `setupOnerror` should be included in the "test framework" section of API.md
- [ ] The `Parameters` entries in the Table of Contents on API.md really mess up the flow of reading the high level APIs that we provide. We should remove them...

### PR DESCRIPTION
**Pull request by ygongdev**
~~- [x] Moved `setupOnerror` to `Test Framework APIs` section~~
~~- [x] Removed `Parameters` from `Table of Content`~~

Additionally,
~~- [x] Removed `Examples` from `Table of Content`~~
~~- [x] Moved `resetOnerror` to `Test Framework APIs` section~~
~~- [x] Adjust number indexing for anchoring purposes to keep variables sorted.~~

~~Fixes #542~~
EDIT:  The actual solution should be modifying the `documentation` build itself.

### CODE REVIEW

**Comment by ygongdev** [comment]
O just realized that we need to modify the `documentation` build, not the `API.md`

**Comment by ygongdev** [comment]
Currently, the `documentation` module doesn't support modifying the `Table of Content`'s `depth`.
However, it seems like a quick trivial change. I created a small PR on `documentation` to try to get this going, https://github.com/documentationjs/documentation/pull/1215.

**Comment by rwjblue** [comment]
Sounds great! Thanks for working on this!

**Comment by ygongdev** [comment]
@rwjblue `documentation` just merged my PR and released a new version. 
Let me know if the `API.md` looks like what we want.

**Comment by rwjblue** [comment]
This looks great! Thank you for working on this!

There is a conflict in `yarn.lock`, if you could rebase and correct it I'll happily merge...

**Comment by ygongdev** [comment]
Rebased.

**Pull request merged**
