### PR TITLE
#351 Adding context for find and findAll helpers

### PR DESCRIPTION
**Pull request by jbingham94**
I added an optional context param to both the find and findAll helpers.  This was a helpful feature in ember-native-dom-helpers, allowing one to write very clean and readable test loops.  I also tightened up the test code a bit for both helpers.

### CODE REVIEW

**Comment by rwjblue** [comment]
See conversation in https://github.com/emberjs/ember-test-helpers/pull/313, I do not believe this is a direction we want to go...

**Comment by jbingham94** [comment]
Hey @rwjblue.  While I understand that it is theoretically possible to have some of the same behavior by using a more complicated selector, it's just not as elegant.  Also, it doesn't work in all cases.  Suppose you want to query within a specific element, not just the first element with a given selector.  Maybe you could use nth-of-type, but it just gets messier and messier the more you try to stuff in that big selector.  Honestly, you could do most things in this library (and definitely in the find and findAll helpers) just using built-in Javascript, but the point is to give developers a more concise way of writing things.  So I'm not really sure I follow your argument that the context parameter is superfluous

**Comment by rwjblue** [comment]
In general folks should be using `element.querySelector`directly, and only using `find` as a last resort. If you have a context element already, just do `context.querySelector` or `context.querySelectorAll`. 

More generally though, this library is all about basic primitives. I think the primitives already exist to support this need. It seems quite trivial to create an addon that makes a `findFrom` or `findWithContext` that works _exactly_ how you want here, and have that addon leverage `find` or `findAll` from `@ember/test-helpers` (or `getRootElement()` and `.querySelector` directly).

**Comment by jbingham94** [comment]
@rwjblue Thanks for the explanation!  I understand your argument from the other PR better now.  I will close this out.

**Pull request closed without merging**
