### PR TITLE
Stop transpiling non-existent vendor tree

### LINKED ISSUE #1048: Expected Broccoli node, got undefined for inputNodes[0]
After upgrading from 2.2.6 to 2.2.7 we see the following build failure (regular build, no embroider):

```
TypeError: broccoli-persistent-filter:Babel > [Babel: @ember/test-helpers] (Babel: @ember/test-helpers): Expected Broccoli node, got undefined for inputNodes[0]
    at Babel.Plugin (/builds/qonto/qonto-js/node_modules/broccoli-plugin/index.js:23:13)
    at Babel.Filter [as constructor] (/builds/qonto/qonto-js/node_modules/broccoli-persistent-filter/index.js:87:10)
    at new Babel (/builds/qonto/qonto-js/node_modules/broccoli-babel-transpiler/index.js:58:10)
    at Class.transpileTree (/builds/qonto/qonto-js/node_modules/ember-cli-babel/index.js:169:16)
    at Class.treeForVendor (/builds/qonto/qonto-js/node_modules/@ember/test-helpers/index.js:44:43)
    at Class._treeFor (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/addon.js:668:33)
    at Class.treeFor (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/addon.js:628:21)
    at /builds/qonto/qonto-js/node_modules/ember-cli/lib/broccoli/ember-app.js:697:26
    at Array.reduce (<anonymous>:null:null)
    at EmberApp._addonTreesFor (/builds/qonto/qonto-js/node_modules/ember-cli/lib/broccoli/ember-app.js:695:32)
    at EmberApp.addonTreesFor (/builds/qonto/qonto-js/node_modules/ember-cli/lib/broccoli/ember-app.js:719:17)
    at EmberApp.getExternalTree (/builds/qonto/qonto-js/node_modules/ember-cli/lib/broccoli/ember-app.js:1177:30)
    at EmberApp.toArray (/builds/qonto/qonto-js/node_modules/ember-cli/lib/broccoli/ember-app.js:1540:12)
    at EmberApp.toTree (/builds/qonto/qonto-js/node_modules/ember-cli/lib/broccoli/ember-app.js:1644:36)
    at EmberApp.appInstance.toTree (/builds/qonto/qonto-js/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at EmberApp.appInstance.toTree (/builds/qonto/qonto-js/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at EmberApp.appInstance.toTree (/builds/qonto/qonto-js/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at EmberApp.appInstance.toTree (/builds/qonto/qonto-js/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at EmberApp.appInstance.toTree (/builds/qonto/qonto-js/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at EmberApp.appInstance.toTree (/builds/qonto/qonto-js/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at EmberApp.appInstance.toTree (/builds/qonto/qonto-js/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at EmberApp.appInstance.toTree (/builds/qonto/qonto-js/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at EmberApp.appInstance.toTree (/builds/qonto/qonto-js/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at EmberApp.appInstance.toTree (/builds/qonto/qonto-js/node_modules/ember-cli-mirage/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at EmberApp.appInstance.toTree (/builds/qonto/qonto-js/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at EmberApp.appInstance.toTree (/builds/qonto/qonto-js/node_modules/ember-exam/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at EmberApp.appInstance.toTree (/builds/qonto/qonto-js/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at EmberApp.appInstance.toTree (/builds/qonto/qonto-js/node_modules/ember-classic-decorator/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at module.exports (/builds/qonto/qonto-js/ember-cli-build.js:142:14)
    at Builder.readBuildFile (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/builder.js:63:22)
    at new Builder (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/builder.js:29:10)
    at BuildTask.run (/builds/qonto/qonto-js/node_modules/ember-cli/lib/tasks/build.js:13:19)
    at /builds/qonto/qonto-js/node_modules/ember-cli/lib/models/command.js:238:24
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Class.run (/builds/qonto/qonto-js/node_modules/ember-cli/lib/commands/test.js:197:7)
    at /builds/qonto/qonto-js/node_modules/ember-cli/lib/cli/cli.js:204:32
    at CLI.run (/builds/qonto/qonto-js/node_modules/ember-cli/lib/cli/cli.js:251:14)
    at module.exports (/builds/qonto/qonto-js/node_modules/ember-cli/lib/cli/index.js:145:12)
```

/cc @rwjblue @stefanpenner

### PR DESCRIPTION
**Pull request by simonihmig**
Fixes #1048

### CODE REVIEW

**Comment by richgt** [comment]
Appreciate the fix, but why did this not fail `ember-try` in its own tests (it seems to break `ember-try` everywhere else...)? Can we create a test that would have failed here so this doesn't break again later?

**Review by richgt — APPROVED** [review]
Approving since it seems to be blocking many people. Would love to see a test as a followup.

**Comment by rwjblue** [comment]
ZOMG, so sorry for this!!! I totally didn't look for an open PR when I opened #1050 🤦 

I'm releasing that fix now

**Comment by rwjblue** [comment]
> Approving since it seems to be blocking many people. Would love to see a test as a followup.

Ya, totally agree. I'm going to try to diagnose why this didn't fail our own CI.

**Comment by rwjblue** [comment]
Fix released as 2.2.8, sorry about this folks :(

**Pull request closed without merging**
