### PR TITLE
dom/-to-array.ts replaced with Array.from()

### PR DESCRIPTION
**Pull request by izelnakri**
Removed redundant code. We can now use native `Array.from()`.

### CODE REVIEW

**Comment by rwjblue** [comment]
> We can now use native Array.from().

Hmm, I didn't think that `Array.from` was supported by IE11 🤔

**Comment by izelnakri** [comment]
> Hmm, I didn't think that `Array.from` was supported by IE11

Yes its still not supported, however the current browser support is 94.59%: https://caniuse.com/?search=Array.from

Array.from is easy to shim, and native `Array.from` must be much faster since its native, thats why I removed it.

**Comment by rwjblue** [comment]
Sure, but we still support IE11 (and do not require a polyfill).

**Comment by izelnakri** [comment]
@rwjblue closed in favor for polyfilled implementation: https://github.com/emberjs/ember-test-helpers/pull/949

**Pull request closed without merging**
