### PR TITLE
Tests: Make valid-jsdoc an error (instead of warning)

### PR DESCRIPTION
**Pull request by rwjblue**
Now that the documentation is updated, this makes it an error...

### CODE REVIEW

**Comment by Turbo87** [comment]
FWIW `documentation` also has a `lint` command 🤔

**Comment by rwjblue** [comment]
Hmm, what does it do?

**Comment by rwjblue** [comment]
I'll add a lint script for it and add it to the initial linting build...

**Comment by Turbo87** [comment]
I think it does something similar, just not sure why they recommend the ESLint rule in their docs... using both can't hurt though

**Pull request merged**
