### PR TITLE
Sync with the v2.x branch

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Some confusing comparisons:
 - https://github.com/emberjs/ember-test-helpers/compare/master...v2.9.3
 - https://github.com/emberjs/ember-test-helpers/compare/v2-x
 
I reviewed the code with the following commits, starting with the first one I did not see in my skim of the t`git log` on `master`:
 - https://github.com/emberjs/ember-test-helpers/commit/1d22a8e8c6b54bf02e9cf34a2c6867be1c94ea25
 - https://github.com/emberjs/ember-test-helpers/commit/a34c29b71d88cb16a876900ce657366916da08ba
 - https://github.com/emberjs/ember-test-helpers/commit/e3f1cb845d27e762ffc15983675086beece2c787
 - https://github.com/emberjs/ember-test-helpers/commit/421d2a03c9f20ee40e8d6eb1ec19e9febaa5bb8f
 - https://github.com/emberjs/ember-test-helpers/commit/20c6cf9a6a8303b683ab28cba9c2c29b6fc7a5d9
 - https://github.com/emberjs/ember-test-helpers/commit/51804d70be134de6fa9fd0421ae10d8de1863074
 
 the only changes missing that I could find that was missing (from looking at the diff of each commit and checking if the code on `master` matched) was the changelog / package.json changes.

### CODE REVIEW

**Review by bertdeblock — APPROVED** [review]

**Comment by NullVoxPopuli** [comment]
Can someone re-run the build here? https://github.com/emberjs/ember-test-helpers/actions/runs/4516904757/jobs/7955705788?pr=1361

The failure is sus, based on the changes in this PR

**Comment by MelSumner** [comment]
I don't think I can re-run the test, been too long maybe? @NullVoxPopuli can you make sure this is branch is updated with current master and re-push? That should jiggle things to get them running.

**Comment by NullVoxPopuli** [comment]
looks like an extra commit snuck in, idk how that happened
gonna remove it

**Review by MelSumner — APPROVED** [review]
🎉 Thank you!

**Pull request merged**
